name: gh-action-continuous-integration-linter-lynt
on: [push, pull_request]

jobs:
  gh-action-continuous-integration-linter-lynt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install
        run: npm install -g lynt@latest

      - name: Run
        run: lynt --fix --all --ignore-path .lyntignore --config .lynt.json --verbose

      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply linter fixes"
          git push
